### PR TITLE
Fixed nested parent issue

### PR DESCRIPTION
**Pull request by adam-codeberg**
Matchdict used for nesting was not being passed to pyramid when requesting the objects route.

### CODE REVIEW

**Comment by adam-codeberg** [comment]
The tests don't look right. Are you able to investigate?

**Comment by adam-codeberg** [comment]
Yeah, travis is making me sad :(

**Comment by adam-codeberg** [comment]
Looks like the test for wrapper.py needs to be amended.

**Comment by jstoiko** [comment]
Thanks for the PR. Yes, tests need to pass. Also noticed, you pushed some files under `.ropeproject/` subfolder, I believe by mistake. Those need to be removed from the PR.

**Comment by adam-codeberg** [comment]
The tests seem to be out of sync with the codebase they're in.
I've restored my local environment to the stable branch and its failing 2 of the 3 tests.

**Comment by postatum** [comment]
@adam-codeberg good job! Thanks for the PR. Failing tests in Travis seem to have different error messages. And looks like they fail then the wrapper that is edited in this PR.
PR looks good.

**Comment by adam-codeberg** [comment]
Thanks. If you can see anything in my changes that may be causing the test fail let me know. The tests seem to be failing on things that are processed before the modified function is called, so I'm at a loss.

**Comment by postatum** [comment]
@adam-codeberg Thanks again for this PR.

I've moved your changes along with few my fixes to this PR https://github.com/brandicted/nefertari/pull/125

**Pull request closed without merging**
