### PR TITLE
Fix nested parent issue

### PR DESCRIPTION
**Pull request by postatum**

### CODE REVIEW

**Comment by adam-codeberg** [comment]
CLA signed.

**Comment by jstoiko** [comment]
@adam-codeberg: do you know who @abyssusj is? he/she appears as "co-commiter" on some of your changes. See: https://github.com/brandicted/nefertari/pull/125/commits

I think that's why it does not pass CLA check. Can @abyssusj sign as well?

**Comment by abyssusj** [comment]
I've also signed it.

**Comment by jstoiko** [comment]
👍

**Pull request merged**
